import {
  iconH1,
  iconH2,
  iconH3,
  iconH4,
  fb,
  ig,
  tw,
  membership,
  merryPink,
  complaint,
  profile,
  basic,
  platinum,
  premium,
  rightIcon,
  profileUser,
  profileUser2,
  profileUser3,
  memberPink,
  complaintPink,
} from "../assets/indexAsset";

export const complaintMockup = [
  {
    username: "John",
    issue: "Internet Connection Problem",
    description: "Unable to connect to the internet.",
    submitDate: "2023-10-11",
    status: "New",
  },
  {
    username: "Mary",
    issue: "Billing Error",
    description: "Incorrect charges on the billing statement.",
    submitDate: "2023-10-10",
    status: "Pending",
  },
  {
    username: "David",
    issue: "Hardware Malfunction",
    description: "Laptop hardware issue, needs repair.",
    submitDate: "2023-10-09",
    status: "Resolved",
  },
  {
    username: "Alice",
    issue: "Software Glitch",
    description: "Frequent crashes in the software.",
    submitDate: "2023-10-08",
    status: "New",
  },
  {
    username: "Michael",
    issue: "Account Login Issue",
    description: "Unable to login to the account.",
    submitDate: "2023-10-07",
    status: "Pending",
  },
  {
    username: "Sophie",
    issue: "Email Delivery Problem",
    description: "Emails not being delivered.",
    submitDate: "2023-10-06",
    status: "Resolved",
  },
  {
    username: "Kevin",
    issue: "Phone Signal Problem",
    description: "Poor phone signal in the area.",
    submitDate: "2023-10-05",
    status: "New",
  },
  {
    username: "Laura",
    issue: "Account Hacked",
    description: "Suspected unauthorized access to account.",
    submitDate: "2023-10-04",
    status: "Pending",
  },
  {
    username: "Peter",
    issue: "Website Accessibility",
    description: "Website not accessible on certain browsers.",
    submitDate: "2023-10-03",
    status: "Resolved",
  },
  {
    username: "Sara",
    issue: "Customer Service Response",
    description: "Long waiting time for customer service response.",
    submitDate: "2023-10-02",
    status: "Cancel",
  },
];

export const userInfo = [
  {
    userID: "1",
    profilePictures: [profileUser2, profileUser, profileUser3],
    name: "John nylon",
    dateOfBirth: "2015-08-01",
    age: "20",
    location: "Thailand",
    city: "Canada",
    username: "John12345",
    email: "John12345@gmail.com",
    sexualIdentities: "male",
    racialPreferences: "female",
    sexualPreferences: "asian",
    meetingInterests: "friends",
    hobbies: ["tv", "game", "social"],
    about: "love god",
    billingHistory: [
      {
        Package: {
          icon: platinum,
          title: "Platinum",
          price: "THB 99.00",
          details: [
            { icon: rightIcon, info: "‘Merry’ more than a daily limited" },
            { icon: rightIcon, info: "Up to 45 Merry per day" },
          ],
          limitMatch: 25,
        },
        startPackageTime: "01/10/2023",
        endPackageTime: "01/11/2023",
        packageStatus: true,
      },
      {
        Package: {
          icon: platinum,
          title: "Platinum",
          price: "THB 99.00",
          details: [
            { icon: rightIcon, info: "‘Merry’ more than a daily limited" },
            { icon: rightIcon, info: "Up to 45 Merry per day" },
          ],
          limitMatch: 25,
        },
        startPackageTime: "01/8/2023",
        endPackageTime: "01/9/2023",
        packageStatus: false,
      },
    ],
  },
  {
    userID: "2",
    profilePictures: [profileUser, profileUser2, profileUser3],
    name: "John",
    age: "45",
    dateOfBirth: "2015-08-01",
    location: "Thailand",
    city: "Canada",
    username: "John12345",
    email: "John12345@gmail.com",
    sexualIdentities: "male",
    racialPreferences: "male",
    sexualPreferences: "asian",
    meetingInterests: "friends",
    hobbies: ["tv", "game", "social"],
    about: "love god",
    billingHistory: [
      {
        Package: {
          icon: platinum,
          title: "Platinum",
          price: "THB 99.00",
          details: [
            { icon: rightIcon, info: "‘Merry’ more than a daily limited" },
            { icon: rightIcon, info: "Up to 45 Merry per day" },
          ],
          limitMatch: 25,
        },
        startPackageTime: "01/10/2023",
        endPackageTime: "01/11/2023",
        packageStatus: true,
      },
      {
        Package: {
          icon: platinum,
          title: "Platinum",
          price: "THB 99.00",
          details: [
            { icon: rightIcon, info: "‘Merry’ more than a daily limited" },
            { icon: rightIcon, info: "Up to 45 Merry per day" },
          ],
          limitMatch: 25,
        },
        startPackageTime: "01/8/2023",
        endPackageTime: "01/9/2023",
        packageStatus: false,
      },
    ],
  },
  {
    userID: "3",
    profilePictures: [profileUser3, profileUser, profileUser2],
    name: "Lufy",
    dateOfBirth: "2015-08-01",
    age: "30",
    location: "Thailand",
    city: "Canada",
    username: "John12345",
    email: "John12345@gmail.com",
    sexualIdentities: "male",
    racialPreferences: "male",
    sexualPreferences: "asian",
    meetingInterests: "friends",
    hobbies: ["tv", "game", "social"],
    about: "love god",
    billingHistory: [
      {
        Package: {
          icon: platinum,
          title: "Platinum",
          price: "THB 99.00",
          details: [
            { icon: rightIcon, info: "‘Merry’ more than a daily limited" },
            { icon: rightIcon, info: "Up to 45 Merry per day" },
          ],
          limitMatch: 25,
        },
        startPackageTime: "01/10/2023",
        endPackageTime: "01/11/2023",
        packageStatus: true,
      },
      {
        Package: {
          icon: platinum,
          title: "Platinum",
          price: "THB 99.00",
          details: [
            { icon: rightIcon, info: "‘Merry’ more than a daily limited" },
            { icon: rightIcon, info: "Up to 45 Merry per day" },
          ],
          limitMatch: 25,
        },
        startPackageTime: "01/8/2023",
        endPackageTime: "01/9/2023",
        packageStatus: false,
      },
    ],
  },
  {
    userID: "4",
    profilePictures: [profileUser3, profileUser, profileUser2],
    name: "Danny",
    dateOfBirth: "2015-08-01",
    age: "30",
    location: "Thailand",
    city: "Canada",
    username: "John12345",
    email: "John12345@gmail.com",
    sexualIdentities: "male",
    racialPreferences: "male",
    sexualPreferences: "asian",
    meetingInterests: "friends",
    hobbies: ["tv", "game", "social"],
    about: "love god",
    billingHistory: [
      {
        Package: {
          icon: platinum,
          title: "Platinum",
          price: "THB 99.00",
          details: [
            { icon: rightIcon, info: "‘Merry’ more than a daily limited" },
            { icon: rightIcon, info: "Up to 45 Merry per day" },
          ],
          limitMatch: 25,
        },
        startPackageTime: "01/10/2023",
        endPackageTime: "01/11/2023",
        packageStatus: true,
      },
      {
        Package: {
          icon: platinum,
          title: "Platinum",
          price: "THB 99.00",
          details: [
            { icon: rightIcon, info: "‘Merry’ more than a daily limited" },
            { icon: rightIcon, info: "Up to 45 Merry per day" },
          ],
          limitMatch: 25,
        },
        startPackageTime: "01/8/2023",
        endPackageTime: "01/9/2023",
        packageStatus: false,
      },
    ],
  },
];

export const matchInfo = [
  {
    matchID: "15987",
    userID: "741",
    matchStatus: false,
    merryToday: true,
    coupleMatch: {
      userID: "123",
      profilePictures: [profileUser, profileUser2, profileUser3],
      name: "John",
      dateOfBirth: "2015-08-01",
      location: "Thailand",
      city: "Canada",
      username: "John12345",
      email: "John12345@gmail.com",
      sexualIdentities: "male",
      racialPreferences: "male",
      sexualPreferences: "asian",
      meetingInterests: "friends",
      hobbies: ["tv", "game", "social"],
      about: "love god",
    },
  },
  {
    matchID: "15988",
    userID: "852",
    matchStatus: true,
    merryToday: false,
    coupleMatch: {
      userID: "123",
      profilePictures: [profileUser, profileUser2, profileUser3],
      name: "John",
      dateOfBirth: "2015-08-01",
      location: "Thailand",
      city: "Canada",
      username: "John12345",
      email: "John12345@gmail.com",
      sexualIdentities: "male",
      racialPreferences: "male",
      sexualPreferences: "asian",
      meetingInterests: "friends",
      hobbies: ["tv", "game", "social"],
      about: "love god",
    },
  },
  {
    matchID: "15989",
    userID: "963",
    matchStatus: true,
    merryToday: true,
    coupleMatch: {
      userID: "123",
      profilePictures: [profileUser, profileUser2, profileUser3],
      name: "John",
      dateOfBirth: "2015-08-01",
      location: "Thailand",
      city: "Canada",
      username: "John12345",
      email: "John12345@gmail.com",
      sexualIdentities: "male",
      racialPreferences: "male",
      sexualPreferences: "asian",
      meetingInterests: "friends",
      hobbies: ["tv", "game", "social"],
      about: "love god",
    },
  },
  {
    matchID: "15990",
    userID: "456",
    matchStatus: true,
    merryToday: true,
    coupleMatch: {
      userID: "123",
      profilePictures: [profileUser, profileUser2, profileUser3],
      name: "John",
      dateOfBirth: "2015-08-01",
      location: "Thailand",
      city: "Canada",
      username: "John12345",
      email: "John12345@gmail.com",
      sexualIdentities: "male",
      racialPreferences: "male",
      sexualPreferences: "asian",
      meetingInterests: "friends",
      hobbies: ["tv", "game", "social"],
      about: "love god",
    },
  },
];

export const allPackage = [
  {
    icon: basic,
    title: "Basic",
    price: "THB 59.00",
    startMemberShip: "01/04/2022",
    details: ["‘Merry’ more than a daily limited", "Up to 25 Merry per day"],
    billingHistory: [
      {
        endPackageTime: "01/08/2022",
        price: "THB 59.00",
      },
      {
        endPackageTime: "01/07/2022",
        price: "THB 59.00",
      },
      {
        endPackageTime: "01/06/2022",
        price: "THB 59.00",
      },
      {
        endPackageTime: "01/06/2022",
        price: "THB 59.00",
      },
      {
        endPackageTime: "01/06/2022",
        price: "THB 59.00",
      },
      {
        endPackageTime: "01/06/2022",
        price: "THB 59.00",
      },
      {
        endPackageTime: "01/06/2022",
        price: "THB 59.00",
      },
    ],
  },
  {
    icon: platinum,
    title: "Platinum",
    price: "THB 99.00",
    details: [
      { icon: rightIcon, info: "‘Merry’ more than a daily limited" },
      { icon: rightIcon, info: "Up to 45 Merry per day" },
    ],
  },
  {
    icon: premium,
    title: "Premium",
    price: "THB 149.00",
    details: [
      { icon: rightIcon, info: "‘Merry’ more than a daily limited" },
      { icon: rightIcon, info: "Up to 70 Merry per day" },
    ],
  },
];

export const features = [
  {
    id: "feature-1",
    icon: iconH1,
    title: "Upload your cool picture",
    content: "Lorem ipsum is a placeholder text",
  },
  {
    id: "feature-2",
    icon: iconH2,
    title: "Explore and find the one you like",
    content: "Lorem ipsum is a placeholder text",
  },
  {
    id: "feature-3",
    icon: iconH3,
    title: "Click ‘Merry’ for get to know!",
    content: "Lorem ipsum is a placeholder text",
  },
  {
    id: "feature-4",
    icon: iconH4,
    title: "Start chating and relationship ",
    content: "Lorem ipsum is a placeholder text",
  },
];

export const navLinks = [
  {
    id: "/#section1",
    title: "Why Merry Match?",
  },
  {
    id: "/#section2",
    title: "How to Merry",
  },
];

export const navProfileLinks = [
  {
    id: "1",
    title: "Profile",
    icon: profile,
    path: "/profile",
  },
  {
    id: "2",
    title: "Merry list",
    icon: merryPink,
    path: "/merrylist",
  },
  {
    id: "3",
    title: "Merry Membership",
    icon: memberPink,
    path: "/memberhistory",
  },
  {
    id: "4",
    title: "Compliant",
    icon: complaintPink,
    path: "/complaintpage",
  },
];

export const socialIcon = [
  {
    id: "1",
    icon: fb,
  },
  {
    id: "2",
    icon: ig,
  },
  {
    id: "3",
    icon: tw,
  },
];
